run-name: UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui-test:
    timeout-minutes: 20
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
        
      - name: Set-up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: ui-tests/package-lock.json

      - name: Install Playwright dependencies and Browser
        run: |
          cd ui-tests
          npm ci
          npm install
          npx playwright install --with-deps chromium

      - name: Run Tests
        env:
          CUSTOMER_PASSWORD: ${{ secrets.CUSTOMER_PASSWORD }}  # Reads from Environment Secrets
          CUSTOMER_EMAIL: ${{ vars.CUSTOMER_EMAIL }}             # Reads from Environment Variables
        run: |
          cd ui-tests
          npx playwright test
