run-name: Build and Test

on:
    # push:
    #     branches: [main]
    # pull_request:
    #     branches: [main]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        timeout-minutes: 15 #expected to finish execution with this time and do not hang the job
        steps:
            - name: Get the code
              uses: actions/checkout@v4

            - name: Install Java 17
              uses: actions/setup-java@v4
              with:
                java-version: 17
                distribution: temurin
                cache: maven
            
            # - name: Start Up Application
            #   #  -B runs Maven in batch mode, which is non-interactive and has no colored output
            #   #  --no-transfer-progress (short form -ntp, needs Maven 3.6.1 or later) stops Maven from printing download progress for dependencies.
            #   #  nohup - no hang up command in linux, allows a process to keep running even after you close the terminal, log out, or disconnect from an SSH session
            #   #  & - run command in the back ground and move on to the next step
            #   run: |
            #     cd lab
            #     nohup mvn -B --no-transfer-progress spring-boot:run > spring.log 2>&1 &

            # - name: Perform Health Checks
            #   run: |
            #     timeout 60s bash -c 'until curl -s http://localhost:8080/actuator/health | grep "UP"; do sleep 2; done'

            - name: Run Tests
              run: |
                cd lab
                ls -la
                mvn -B -ntp test

            - name: Build only surefire report
              if: always()
              run: |
                cd lab
                mvn -B -ntp surefire-report:report-only

            - name: Publish Test Report
            #By default, GitHub Actions stops running subsequent steps if a previous step (like running the tests) fails. The always() conditional overrides this behavior. It forces this step to run no matter what—whether the tests passed, failed, or timed out. Without this, if your tests fail, your test reports would never be uploaded, leaving you with no data to debug.
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: surefire-reports
                path: lab/target/reports
                
