name: First workflow file
run-name: This is the first workflow file.
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    orientation:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v4

            - name: Look around the runner
              run: |
                pwd
                ls -la
                java -v || echo "no java"
                node --version || echo "no node"
                echo "Branch: ${{ github.ref_name }} | Event: ${{ github.event_name }}"
    
